// Shared environment variable names used in both web app and functions

export const OPENAI_API_KEY_VAR = 'OPENAI_API_KEY';
export const ANTHROPIC_API_KEY_VAR = 'ANTHROPIC_API_KEY';
export const SITE_DOMAIN_VAR = 'SITE_DOMAIN';
export const LAST_DEPLOY_AFFECTING_RENDERING_VAR = 'LAST_DEPLOY_AFFECTING_RENDERING';
export const TWITTER_ACCESS_TOKEN_SECRET_VAR = 'TWITTER_ACCESS_TOKEN_SECRET';
export const TWITTER_CONSUMER_SECRET_VAR = 'TWITTER_CONSUMER_SECRET';
export const TWITTER_ACCESS_TOKEN_KEY_VAR = 'TWITTER_ACCESS_TOKEN_KEY';
export const TWITTER_CONSUMER_KEY_VAR = 'TWITTER_CONSUMER_KEY';
export const EMAIL_POSTMARK_KEY_VAR = 'EMAIL_POSTMARK_KEY';
export const EMAIL_TO_ADDRESS_VAR = 'EMAIL_TO_ADDRESS';
export const EMAIL_FROM_ADDRESS_VAR = 'EMAIL_FROM_ADDRESS';
export const QDRANT_CLUSTER_URL_VAR = 'QDRANT_CLUSTER_URL';
export const QDRANT_API_KEY_VAR = 'QDRANT_API_KEY';

export const CHAT_POST_MESSAGE_ROUTE = '/postMessage';
export const CHAT_CREATE_MESSAGE_ROUTE = '/create';
export const CHAT_STREAM_MESSAGE_ROUTE = '/streamMessage';
export const CHAT_RETRY_MESSAGE_ROUTE = '/retry';